# task and env
env:
  env_name: CustomContinuousEnv-v0
#  env_name: Hopper-v5

# collector
collector:
  frames_per_batch: 64
  total_frames: 1_000_000

# logger
logger:
  backend: wandb
  mode: online
  project_name: policy_discrete_bandit
  group_name: a2c_oh_64_bandit
  exp_name: a2c_oh_64
  test_interval: 10_000
  num_test_episodes: 5
  video: False
 
network:
  policy_hidden_sizes: [64, 64]

# Optim
optim:
  lr_q: 3e-4
  lr_policy: 3e-4
  weight_decay: 0.0
  anneal_lr: False
  max_grad_norm: 10.0

# loss
loss:
  gamma: 0.99
  mini_batch_size: 64
  gae_lambda: 0.95
  critic_coef: 0.25
  entropy_coef: 0.0
  loss_critic_type: l2
  loss_policy_type: cross_entropy #"l2", "cross_entropy"
  loss_policy_target_type: one_hot #"one_hot", "two_hot", "gauss", "focal"
