# environment and task
env:
  name: Hopper-v5
  task: ""
  library: gymnasium
  max_episode_steps: 1000
  seed: 42

# collector
collector:
  total_frames: 1_000_000
  init_random_frames: 5000
  frames_per_batch: 1
  init_env_steps: 1000
  device: cpu
  env_per_collector: 1
  reset_at_each_iter: False

# replay buffer
replay_buffer:
  size: 1000000
  prb: 0 # use prioritized experience replay
  scratch_dir: null

# optim
optim:
  utd_ratio: 1.0
  gamma: 0.99
  loss_function: l2
  lr_policy: 3.0e-4
  lr_q: 3e-4
  weight_decay: 0.0
  batch_size: 256
  target_update_polyak: 0.995
  alpha_init: 1.0
  adam_eps: 1.0e-8
  max_grad_norm: 10.0

# network
network:
  hidden_sizes_q: [2048, 2048]  
  hidden_sizes_policy: [256, 256]  
  activation: relu
  default_policy_scale: 1.0
  scale_lb: 0.1
  device: "cuda:0"

# logging
logger:
  backend: wandb
  project_name: sac_classification
  group_name: null
  exp_name: ${env.name}_SAC_Gauss
  mode: online
  eval_iter: 2500