# task and env
env:
  env_name: Hopper-v5

# collector
collector:
  frames_per_batch: 64
  total_frames: 1_000_000

# logger
logger:
  backend: wandb
  mode: online
  project_name: policy_discrete
  group_name: a2c_gnc_64_hopper
  exp_name: a2c_gnc_64
  test_interval: 10_000
  num_test_episodes: 5
  video: False

network:
  policy_hidden_sizes: [64, 64]

# Optim
optim:
  lr: 3e-4
  weight_decay: 0.0
  anneal_lr: False
  max_grad_norm: 1.0

# loss
loss:
  gamma: 0.99
  mini_batch_size: 64
  gae_lambda: 0.95
  critic_coef: 0.25
  entropy_coef: 0.0
  loss_critic_type: l2
  loss_policy_type: cross_entropy #"l2", "cross_entropy"
  loss_policy_target_type: gauss #"one_hot", "two_hot", "gauss"
