from .heading_task import HeadingTask
from .singlecombat_task import SingleCombatTask, HierarchicalSingleCombatTask
from .singlecombat_with_missle_task import SingleCombatDodgeMissileTask, HierarchicalSingleCombatDodgeMissileTask, HierarchicalSingleCombatShootTask, SingleCombatShootMissileTask
from .opus_altitude_task import OpusAltitudeTask
from .opus_smoothing_task import OpusSmoothingTask
from .opus_altitude_speed_heading_task import OpusAltitudeSpeedHeadingTask
from .opus_altitude_speed_task import OpusAltitudeSpeedTask